development:
  adapter: postgresql
  database: doubtfire_dev
  username: itig
  password: d872$dh
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  database: doubtfire_test
  username: itig
  password: d872$dh
  host: localhost