development:
  adapter: postgresql
  database: doubtfire_dev
  username: itig
  password: d872$dh
  host:  localhost
  min_messages: warning

test:
  adapter: postgresql
  database: doubtfire_dev_test
  username: itig
  password: d872$dh
  host: localhost
  min_messages: warning

staging:
  adapter:  # staging DB adapter
  host:     # staging DB host
  database: # staging DB
  username: # staging DB username
  password: # staging DB password

production:
  adapter:  # prod DB adapter
  host:     # prod DB host
  database: # prod DB
  username: # prod DB username
  password: # prod DB password
