name:         <%= ENV['DF_INSTITUTION_NAME']         || 'University of Foo' %>
email_domain: <%= ENV['DF_INSTITUTION_EMAIL_DOMAIN'] || 'foo.edu.au' %>
host:         <%= ENV['DF_INSTITUTION_HOST']         || 'doubtfire.ict.foo.edu.au' %>
