name:         <%= ENV['DF_INSTITUTION_NAME']         || 'University of Foo' %>
email_domain: <%= ENV['DF_INSTITUTION_EMAIL_DOMAIN'] || 'doubtfire.com' %>
host:         <%= ENV['DF_INSTITUTION_HOST']         || 'localhost:3000' %>
