development: &DEVELOPMENT
  secret_key_base:   <%= SecureRandom.base64 %>
  secret_key_attr:   <%= SecureRandom.base64 %>
  secret_key_devise: <%= SecureRandom.base64 %>
  secret_key_jwt:    'secret'
test:
  # <<: *DEVELOPMENT
replica:
  # <<: *DEVELOPMENT
production:
  secret_key_base:   <%= ENV['DF_SECRET_KEY_BASE']   %>
  secret_key_attr:   <%= ENV['DF_SECRET_KEY_ATTR']   %>
  secret_key_devise: <%= ENV['DF_SECRET_KEY_DEVISE'] %>
  secret_key_jwt:    <%= ENV['DF_SECRET_KEY_JWT']    %>
